const prisma = require('../../../config/prisma');
const logger = require('../../../config/logger');
const path = require('path');
const fs = require('fs').promises;

// Upload directory (resolve to absolute path)
const UPLOAD_DIR = path.resolve(process.env.UPLOAD_DIR || './uploads');

/**
 * Get all attachments for an entity
 */
const getByEntity = async (entityType, entityUuid) => {
  return prisma.attachments.findMany({
    where: {
      entity_type: entityType,
      entity_uuid: entityUuid,
    },
    orderBy: { created_at: 'desc' },
  });
};

/**
 * Get attachment by UUID
 */
const getByUuid = async (uuid) => {
  return prisma.attachments.findUnique({
    where: { uuid },
  });
};

/**
 * Create a new attachment (file already saved by multer diskStorage)
 */
const create = async (data, file, uploadedByUuid) => {
  // File is already saved by multer, we just need to store metadata in DB
  // file.filename = UUID generated by multer
  // file.path = full path where multer saved the file
  // file.destination = directory where file was saved
  
  // Store relative path (from UPLOAD_DIR)
  const relativePath = path.relative(UPLOAD_DIR, file.path);
  
  const attachment = await prisma.attachments.create({
    data: {
      entity_type: data.entity_type,
      entity_uuid: data.entity_uuid,
      file_name: file.filename,
      original_name: file.originalname,
      mime_type: file.mimetype,
      file_size: file.size,
      file_path: relativePath,
      uploaded_by_uuid: uploadedByUuid,
    },
  });
  
  logger.info(`[ATTACHMENTS] Created attachment: ${attachment.uuid} for ${data.entity_type}/${data.entity_uuid}`);
  return attachment;
};

/**
 * Delete an attachment
 */
const remove = async (uuid) => {
  const attachment = await prisma.attachments.findUnique({
    where: { uuid },
  });
  
  if (!attachment) {
    return false;
  }
  
  // Delete file from disk
  try {
    const filePath = path.join(UPLOAD_DIR, attachment.file_path);
    await fs.unlink(filePath);
  } catch (error) {
    logger.warn(`[ATTACHMENTS] Could not delete file: ${attachment.file_path}`, error);
  }
  
  // Delete from database
  await prisma.attachments.delete({
    where: { uuid },
  });
  
  logger.info(`[ATTACHMENTS] Deleted attachment: ${uuid}`);
  return true;
};

/**
 * Get file path for download
 */
const getFilePath = async (uuid) => {
  logger.info(`[ATTACHMENTS] getFilePath called with uuid: ${uuid}`);
  
  const attachment = await prisma.attachments.findUnique({
    where: { uuid },
  });
  
  logger.info(`[ATTACHMENTS] Attachment found: ${JSON.stringify(attachment)}`);
  
  if (!attachment) {
    logger.warn(`[ATTACHMENTS] Attachment not found for uuid: ${uuid}`);
    return null;
  }
  
  const filePath = path.join(UPLOAD_DIR, attachment.file_path);
  logger.info(`[ATTACHMENTS] File path: ${filePath}`);
  
  return {
    path: filePath,
    originalName: attachment.original_name,
    mimeType: attachment.mime_type,
  };
};

module.exports = {
  getByEntity,
  getByUuid,
  create,
  remove,
  getFilePath,
};
