const { prisma } = require('../client');

/**
 * Seed ticket type fields - Extended fields definition for each ticket type
 * These fields define what attributes are stored in tickets.extended_core_fields
 */
async function seedTicketTypeFields() {
  console.log('Seeding ticket type fields...');

  // Get ticket types UUIDs
  const ticketTypes = await prisma.ticket_types.findMany({
    select: { uuid: true, code: true },
  });

  const ticketTypeMap = {};
  for (const tt of ticketTypes) {
    ticketTypeMap[tt.code] = tt.uuid;
  }

  // Define extended fields for each ticket type
  const fieldsByTicketType = {
    TASK: [
      {
        field_name: 'initial_target_date',
        label: 'Initial Target Date',
        description: 'Original target completion date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        is_required: false,
        is_readonly: false,
        min_width: '10rem',
        display_order: 1,
      },
      {
        field_name: 'revised_target_date',
        label: 'Revised Target Date',
        description: 'Updated target completion date after postponements',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        is_required: false,
        is_readonly: false,
        min_width: '10rem',
        display_order: 2,
      },
      {
        field_name: 'postponement_count',
        label: 'Postponement Count',
        description: 'Number of times the task has been postponed',
        field_type: 'number',
        data_type: 'number',
        show_in_table: true,
        show_in_form: true,
        is_required: false,
        is_readonly: true,
        min_width: '8rem',
        display_order: 3,
        default_value: '0',
      },
    ],
    INCIDENT: [
      {
        field_name: 'symptoms_uuid',
        label: 'Symptoms',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'symptoms',
        relation_display: 'label',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        is_readonly: false,
        display_order: 1,
        min_width: '12rem',
      },
      {
        field_name: 'impact',
        label: 'Impact',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 2,
        min_width: '8rem',
        options_source: '/object-setup/options?object_type=incident&metadata=IMPACT',
      },
      {
        field_name: 'urgency',
        label: 'Urgency',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 3,
        min_width: '8rem',
        options_source: '/object-setup/options?object_type=incident&metadata=URGENCY',
      },
      {
        field_name: 'priority',
        label: 'Priority',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 4,
        min_width: '8rem',
      },
      {
        field_name: 'contact_type',
        label: 'Contact Type',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 5,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=contact&metadata=TYPE',
      },
      {
        field_name: 'service_uuid',
        label: 'Service',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'configuration_items',
        relation_display: 'name',
        relation_filter: { ci_type_code: 'SERVICE' },
        show_in_table: true,
        show_in_form: true,
        display_order: 6,
        min_width: '12rem',
      },
      {
        field_name: 'service_offerings_uuid',
        label: 'Service Offerings',
        field_type: 'relation',
        data_type: 'array',
        relation_object: 'configuration_items',
        relation_display: 'name',
        relation_filter: { ci_type_code: 'SERVICE_OFFERING' },
        show_in_table: false,
        show_in_form: true,
        display_order: 7,
        min_width: '14rem',
      },
      {
        field_name: 'resolution_notes',
        label: 'Resolution Notes',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 10,
        min_width: '20rem',
      },
      {
        field_name: 'resolution_code',
        label: 'Resolution Code',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 11,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=incident&metadata=RESOLUTION_CODE',
      },
      {
        field_name: 'cause_code',
        label: 'Cause Code',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 12,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=incident&metadata=CAUSE_CODE',
      },
      {
        field_name: 'problem_uuid',
        label: 'Related Problem',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'tickets',
        relation_display: 'title',
        relation_filter: { ticket_type_code: 'PROBLEM' },
        show_in_table: false,
        show_in_form: true,
        display_order: 13,
        min_width: '14rem',
      },
      {
        field_name: 'change_uuid',
        label: 'Related Change Request',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'tickets',
        relation_display: 'title',
        relation_filter: { ticket_type_code: 'CHANGE' },
        show_in_table: false,
        show_in_form: true,
        display_order: 14,
        min_width: '14rem',
      },
      {
        field_name: 'sla_assignation_due_at',
        label: 'SLA Assignation Due',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        is_readonly: true,
        display_order: 20,
        min_width: '12rem',
      },
      {
        field_name: 'assigned_to_at',
        label: 'Assigned At',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: false,
        show_in_form: true,
        is_readonly: true,
        display_order: 21,
        min_width: '12rem',
      },
      {
        field_name: 'sla_resolution_due_at',
        label: 'SLA Resolution Due',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        is_readonly: true,
        display_order: 22,
        min_width: '12rem',
      },
      {
        field_name: 'resolved_at',
        label: 'Resolved At',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        is_readonly: true,
        display_order: 23,
        min_width: '12rem',
      },
      {
        field_name: 'reopen_count',
        label: 'Reopen Count',
        field_type: 'number',
        data_type: 'number',
        show_in_table: true,
        show_in_form: true,
        is_readonly: true,
        display_order: 30,
        min_width: '8rem',
        default_value: '0',
      },
      {
        field_name: 'assignment_count',
        label: 'Assignment Count',
        field_type: 'number',
        data_type: 'number',
        show_in_table: false,
        show_in_form: true,
        is_readonly: true,
        display_order: 31,
        min_width: '8rem',
        default_value: '0',
      },
      {
        field_name: 'assignment_to_count',
        label: 'Assignment To Count',
        field_type: 'number',
        data_type: 'number',
        show_in_table: false,
        show_in_form: true,
        is_readonly: true,
        display_order: 32,
        min_width: '8rem',
        default_value: '0',
      },
      {
        field_name: 'standby_count',
        label: 'Standby Count',
        field_type: 'number',
        data_type: 'number',
        show_in_table: false,
        show_in_form: true,
        is_readonly: true,
        display_order: 33,
        min_width: '8rem',
        default_value: '0',
      },
    ],
    PROBLEM: [
      {
        field_name: 'rel_problem_categories_code',
        label: 'Problem Category',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 1,
        min_width: '12rem',
        options_source: '/object-setup/options?object_type=problem&metadata=CATEGORY',
      },
      {
        field_name: 'impact',
        label: 'Impact',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 2,
        min_width: '8rem',
        options_source: '/object-setup/options?object_type=incident&metadata=IMPACT',
      },
      {
        field_name: 'urgency',
        label: 'Urgency',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 3,
        min_width: '8rem',
        options_source: '/object-setup/options?object_type=incident&metadata=URGENCY',
      },
      {
        field_name: 'service_uuid',
        label: 'Service',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'configuration_items',
        relation_display: 'name',
        relation_filter: { ci_type_code: 'SERVICE' },
        show_in_table: true,
        show_in_form: true,
        display_order: 4,
        min_width: '12rem',
      },
      {
        field_name: 'service_offerings_uuid',
        label: 'Service Offerings',
        field_type: 'relation',
        data_type: 'array',
        relation_object: 'configuration_items',
        relation_display: 'name',
        relation_filter: { ci_type_code: 'SERVICE_OFFERING' },
        show_in_table: false,
        show_in_form: true,
        display_order: 5,
        min_width: '14rem',
      },
      {
        field_name: 'symptoms_description',
        label: 'Symptoms Description',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 10,
        min_width: '20rem',
      },
      {
        field_name: 'workaround',
        label: 'Workaround',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 11,
        min_width: '20rem',
      },
      {
        field_name: 'root_cause',
        label: 'Root Cause',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 12,
        min_width: '20rem',
      },
      {
        field_name: 'definitive_solution',
        label: 'Definitive Solution',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 13,
        min_width: '20rem',
      },
      {
        field_name: 'target_resolution_date',
        label: 'Target Resolution Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 20,
        min_width: '10rem',
      },
      {
        field_name: 'actual_resolution_date',
        label: 'Actual Resolution Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 21,
        min_width: '10rem',
      },
      {
        field_name: 'actual_resolution_workload',
        label: 'Actual Resolution Workload',
        field_type: 'number',
        data_type: 'number',
        show_in_table: true,
        show_in_form: true,
        display_order: 22,
        min_width: '8rem',
        unit: 'hours',
      },
      {
        field_name: 'closure_justification',
        label: 'Closure Justification',
        field_type: 'text',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 30,
        min_width: '20rem',
      },
    ],
    PROJECT: [
      {
        field_name: 'key',
        label: 'Project Key',
        description: 'Unique project identifier code',
        field_type: 'text',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 1,
        min_width: '8rem',
        max_length: 10,
      },
      {
        field_name: 'start_date',
        label: 'Start Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 2,
        min_width: '10rem',
      },
      {
        field_name: 'end_date',
        label: 'End Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 3,
        min_width: '10rem',
      },
      {
        field_name: 'visibility',
        label: 'Visibility',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 5,
        min_width: '10rem',
        options_source: JSON.stringify([
          { label: 'Public', value: 'PUBLIC' },
          { label: 'Private', value: 'PRIVATE' },
          { label: 'Restricted', value: 'RESTRICTED' },
        ]),
      },
      {
        field_name: 'project_type',
        label: 'Project Type',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 6,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=project&metadata=CATEGORY',
      },
      {
        field_name: 'access_to_groups',
        label: 'Access Groups',
        field_type: 'relation',
        data_type: 'array',
        relation_object: 'groups',
        relation_display: 'group_name',
        show_in_table: false,
        show_in_form: true,
        display_order: 10,
        min_width: '14rem',
      },
      {
        field_name: 'access_to_users',
        label: 'Access Users',
        field_type: 'relation',
        data_type: 'array',
        relation_object: 'persons',
        relation_display: 'last_name',
        show_in_table: false,
        show_in_form: true,
        display_order: 11,
        min_width: '14rem',
      },
    ],
    // ========================================
    // CHANGE - Change Management
    // ========================================
    CHANGE: [
      {
        field_name: 'rel_change_type_code',
        label: 'Change Type',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 1,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=change&metadata=TYPE',
      },
      {
        field_name: 'service_uuid',
        label: 'Service',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'configuration_items',
        relation_display: 'name',
        relation_filter: { ci_type_code: 'SERVICE' },
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 2,
        min_width: '12rem',
      },
      {
        field_name: 'service_offerings_uuid',
        label: 'Service Offerings',
        field_type: 'relation',
        data_type: 'array',
        relation_object: 'configuration_items',
        relation_display: 'name',
        relation_filter: { ci_type_code: 'SERVICE_OFFERING' },
        show_in_table: false,
        show_in_form: true,
        display_order: 3,
        min_width: '14rem',
      },
      // Risk Assessment Questions
      {
        field_name: 'r_q1',
        label: 'Risk Question 1',
        field_type: 'select',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 10,
        min_width: '10rem',
        options_source: '/change_options?question_id=r_q1',
      },
      {
        field_name: 'r_q2',
        label: 'Risk Question 2',
        field_type: 'select',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 11,
        min_width: '10rem',
        options_source: '/change_options?question_id=r_q2',
      },
      {
        field_name: 'r_q3',
        label: 'Risk Question 3',
        field_type: 'select',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 12,
        min_width: '10rem',
        options_source: '/change_options?question_id=r_q3',
      },
      {
        field_name: 'r_q4',
        label: 'Risk Question 4',
        field_type: 'select',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 13,
        min_width: '10rem',
        options_source: '/change_options?question_id=r_q4',
      },
      {
        field_name: 'r_q5',
        label: 'Risk Question 5',
        field_type: 'select',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 14,
        min_width: '10rem',
        options_source: '/change_options?question_id=r_q5',
      },
      // Impact Assessment Questions
      {
        field_name: 'i_q1',
        label: 'Impact Question 1',
        field_type: 'select',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 20,
        min_width: '10rem',
        options_source: '/change_options?question_id=i_q1',
      },
      {
        field_name: 'i_q2',
        label: 'Impact Question 2',
        field_type: 'select',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 21,
        min_width: '10rem',
        options_source: '/change_options?question_id=i_q2',
      },
      {
        field_name: 'i_q3',
        label: 'Impact Question 3',
        field_type: 'select',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 22,
        min_width: '10rem',
        options_source: '/change_options?question_id=i_q3',
      },
      {
        field_name: 'i_q4',
        label: 'Impact Question 4',
        field_type: 'select',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 23,
        min_width: '10rem',
        options_source: '/change_options?question_id=i_q4',
      },
      // Planning
      {
        field_name: 'requested_start_date_at',
        label: 'Requested Start Date',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 30,
        min_width: '12rem',
      },
      {
        field_name: 'requested_end_date_at',
        label: 'Requested End Date',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 31,
        min_width: '12rem',
      },
      {
        field_name: 'planned_start_date_at',
        label: 'Planned Start Date',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 32,
        min_width: '12rem',
      },
      {
        field_name: 'planned_end_date_at',
        label: 'Planned End Date',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 33,
        min_width: '12rem',
      },
      {
        field_name: 'rel_change_justifications_code',
        label: 'Justification',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 34,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=change&metadata=JUSTIFICATION',
      },
      {
        field_name: 'rel_change_objective',
        label: 'Objective',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 35,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=change&metadata=OBJECTIVE',
      },
      {
        field_name: 'test_plan',
        label: 'Test Plan',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 40,
        min_width: '20rem',
      },
      {
        field_name: 'implementation_plan',
        label: 'Implementation Plan',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 41,
        min_width: '20rem',
      },
      {
        field_name: 'rollback_plan',
        label: 'Rollback Plan',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 42,
        min_width: '20rem',
      },
      {
        field_name: 'post_implementation_plan',
        label: 'Post Implementation Plan',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 43,
        min_width: '20rem',
      },
      // Validation
      {
        field_name: 'cab_comments',
        label: 'CAB Comments',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 50,
        min_width: '20rem',
      },
      {
        field_name: 'rel_cab_validation_status',
        label: 'CAB Validation Status',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 51,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=change&metadata=CAB_VALIDATION_STATUS',
      },
      {
        field_name: 'validated_at',
        label: 'Validated At',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        is_readonly: true,
        display_order: 52,
        min_width: '12rem',
      },
      // Execution
      {
        field_name: 'actual_start_date_at',
        label: 'Actual Start Date',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 60,
        min_width: '12rem',
      },
      {
        field_name: 'actual_end_date_at',
        label: 'Actual End Date',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 61,
        min_width: '12rem',
      },
      {
        field_name: 'elapsed_time',
        label: 'Elapsed Time',
        field_type: 'number',
        data_type: 'number',
        show_in_table: true,
        show_in_form: true,
        is_readonly: true,
        display_order: 62,
        min_width: '8rem',
        unit: 'minutes',
      },
      // Closure
      {
        field_name: 'success_criteria',
        label: 'Success Criteria',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 70,
        min_width: '20rem',
      },
      {
        field_name: 'post_change_evaluation',
        label: 'Post Change Evaluation',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 71,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=change&metadata=POST_IMPLEMENTATION_EVALUATION',
      },
      {
        field_name: 'post_change_comment',
        label: 'Post Change Comment',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 72,
        min_width: '20rem',
      },
    ],
    // ========================================
    // KNOWLEDGE - Knowledge Articles
    // ========================================
    KNOWLEDGE: [
      {
        field_name: 'rel_category',
        label: 'Category',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 1,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=knowledge&metadata=CATEGORY',
      },
      {
        field_name: 'summary',
        label: 'Summary',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 2,
        min_width: '20rem',
      },
      {
        field_name: 'keywords',
        label: 'Keywords',
        field_type: 'tags',
        data_type: 'array',
        show_in_table: true,
        show_in_form: true,
        display_order: 3,
        min_width: '14rem',
      },
      {
        field_name: 'prerequisites',
        label: 'Prerequisites',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 10,
        min_width: '20rem',
      },
      {
        field_name: 'limitations',
        label: 'Limitations',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 11,
        min_width: '20rem',
      },
      {
        field_name: 'security_notes',
        label: 'Security Notes',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 12,
        min_width: '20rem',
      },
      {
        field_name: 'service_uuid',
        label: 'Service',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'configuration_items',
        relation_display: 'name',
        relation_filter: { ci_type_code: 'SERVICE' },
        show_in_table: true,
        show_in_form: true,
        display_order: 20,
        min_width: '12rem',
      },
      {
        field_name: 'service_offerings_uuid',
        label: 'Service Offerings',
        field_type: 'relation',
        data_type: 'array',
        relation_object: 'configuration_items',
        relation_display: 'name',
        relation_filter: { ci_type_code: 'SERVICE_OFFERING' },
        show_in_table: false,
        show_in_form: true,
        display_order: 21,
        min_width: '14rem',
      },
      {
        field_name: 'rel_involved_process',
        label: 'Involved Process',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 22,
        min_width: '10rem',
        options_source: '/ticket_types',
      },
      {
        field_name: 'rel_target_audience',
        label: 'Target Audience',
        field_type: 'tags',
        data_type: 'array',
        show_in_table: true,
        show_in_form: true,
        display_order: 23,
        min_width: '14rem',
        options_source: '/object-setup/options?object_type=knowledge&metadata=TARGET_AUDIENCE',
      },
      {
        field_name: 'business_scope',
        label: 'Business Scope',
        field_type: 'tags',
        data_type: 'array',
        show_in_table: true,
        show_in_form: true,
        display_order: 24,
        min_width: '14rem',
        options_source: '/object-setup/options?object_type=knowledge&metadata=BUSINESS_SCOPE',
      },
      {
        field_name: 'rel_lang',
        label: 'Language',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 30,
        min_width: '8rem',
        options_source: '/languages?is_active=yes',
      },
      {
        field_name: 'rel_confidentiality_level',
        label: 'Confidentiality Level',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 31,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=knowledge&metadata=CONFIDENTIALITY_LEVEL',
      },
      {
        field_name: 'version',
        label: 'Version',
        field_type: 'text',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 32,
        min_width: '6rem',
      },
      {
        field_name: 'last_review_at',
        label: 'Last Review Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 40,
        min_width: '10rem',
      },
      {
        field_name: 'next_review_at',
        label: 'Next Review Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 41,
        min_width: '10rem',
      },
      {
        field_name: 'license_type',
        label: 'License Type',
        field_type: 'text',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 42,
        min_width: '10rem',
      },
    ],
    // ========================================
    // USER_STORY - Agile User Stories
    // ========================================
    USER_STORY: [
      {
        field_name: 'project_uuid',
        label: 'Project',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'tickets',
        relation_display: 'title',
        relation_filter: { ticket_type_code: 'PROJECT' },
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 1,
        min_width: '12rem',
      },
      {
        field_name: 'epic_uuid',
        label: 'Epic',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'tickets',
        relation_display: 'title',
        relation_filter: { ticket_type_code: 'EPIC' },
        show_in_table: true,
        show_in_form: true,
        display_order: 2,
        min_width: '12rem',
      },
      {
        field_name: 'sprint_uuid',
        label: 'Sprint',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'tickets',
        relation_display: 'title',
        relation_filter: { ticket_type_code: 'SPRINT' },
        show_in_table: true,
        show_in_form: true,
        display_order: 3,
        min_width: '12rem',
      },
      {
        field_name: 'story_points',
        label: 'Story Points',
        field_type: 'number',
        data_type: 'number',
        show_in_table: true,
        show_in_form: true,
        display_order: 10,
        min_width: '8rem',
      },
      {
        field_name: 'priority',
        label: 'Priority',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 11,
        min_width: '8rem',
        options_source: JSON.stringify([
          { label: 'Highest', value: 'HIGHEST' },
          { label: 'High', value: 'HIGH' },
          { label: 'Medium', value: 'MEDIUM' },
          { label: 'Low', value: 'LOW' },
          { label: 'Lowest', value: 'LOWEST' },
        ]),
      },
      {
        field_name: 'acceptance_criteria',
        label: 'Acceptance Criteria',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 20,
        min_width: '20rem',
      },
      {
        field_name: 'tags',
        label: 'Tags',
        field_type: 'tags',
        data_type: 'array',
        show_in_table: true,
        show_in_form: true,
        display_order: 30,
        min_width: '14rem',
      },
    ],
    // ========================================
    // SPRINT - Agile Sprints
    // ========================================
    SPRINT: [
      {
        field_name: 'project_uuid',
        label: 'Project',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'tickets',
        relation_display: 'title',
        relation_filter: { ticket_type_code: 'PROJECT' },
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 1,
        min_width: '12rem',
      },
      {
        field_name: 'start_date',
        label: 'Start Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 2,
        min_width: '10rem',
      },
      {
        field_name: 'end_date',
        label: 'End Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 3,
        min_width: '10rem',
      },
      {
        field_name: 'estimated_velocity',
        label: 'Estimated Velocity',
        field_type: 'number',
        data_type: 'number',
        show_in_table: true,
        show_in_form: true,
        display_order: 10,
        min_width: '8rem',
      },
      {
        field_name: 'actual_velocity',
        label: 'Actual Velocity',
        field_type: 'number',
        data_type: 'number',
        show_in_table: true,
        show_in_form: true,
        is_readonly: true,
        display_order: 11,
        min_width: '8rem',
      },
    ],
    // ========================================
    // EPIC - Agile Epics
    // ========================================
    EPIC: [
      {
        field_name: 'project_uuid',
        label: 'Project',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'tickets',
        relation_display: 'title',
        relation_filter: { ticket_type_code: 'PROJECT' },
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 1,
        min_width: '12rem',
      },
      {
        field_name: 'start_date',
        label: 'Start Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 2,
        min_width: '10rem',
      },
      {
        field_name: 'end_date',
        label: 'End Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 3,
        min_width: '10rem',
      },
      {
        field_name: 'progress_percent',
        label: 'Progress',
        field_type: 'number',
        data_type: 'number',
        show_in_table: true,
        show_in_form: true,
        is_readonly: true,
        display_order: 10,
        min_width: '8rem',
        unit: '%',
      },
      {
        field_name: 'color',
        label: 'Color',
        field_type: 'text',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 20,
        min_width: '8rem',
      },
      {
        field_name: 'tags',
        label: 'Tags',
        field_type: 'tags',
        data_type: 'array',
        show_in_table: true,
        show_in_form: true,
        display_order: 30,
        min_width: '14rem',
      },
    ],
    // ========================================
    // DEFECT - Bug/Defect Tracking
    // ========================================
    DEFECT: [
      {
        field_name: 'project_uuid',
        label: 'Project',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'tickets',
        relation_display: 'title',
        relation_filter: { ticket_type_code: 'PROJECT' },
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 1,
        min_width: '12rem',
      },
      {
        field_name: 'severity',
        label: 'Severity',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 2,
        min_width: '8rem',
        options_source: '/object-setup/options?object_type=defect&metadata=SEVERITY',
      },
      {
        field_name: 'impact_area',
        label: 'Impact Area',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 3,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=defect&metadata=IMPACT',
      },
      {
        field_name: 'environment',
        label: 'Environment',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 4,
        min_width: '10rem',
        options_source: '/object-setup/options?object_type=defect&metadata=ENVIRONMENT',
      },
      {
        field_name: 'epic_uuid',
        label: 'Epic',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'tickets',
        relation_display: 'title',
        relation_filter: { ticket_type_code: 'EPIC' },
        show_in_table: false,
        show_in_form: true,
        display_order: 5,
        min_width: '12rem',
      },
      {
        field_name: 'sprint_uuid',
        label: 'Sprint',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'tickets',
        relation_display: 'title',
        relation_filter: { ticket_type_code: 'SPRINT' },
        show_in_table: false,
        show_in_form: true,
        display_order: 6,
        min_width: '12rem',
      },
      {
        field_name: 'steps_to_reproduce',
        label: 'Steps to Reproduce',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 10,
        min_width: '20rem',
      },
      {
        field_name: 'expected_behavior',
        label: 'Expected Behavior',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 11,
        min_width: '20rem',
      },
      {
        field_name: 'workaround',
        label: 'Workaround',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 12,
        min_width: '20rem',
      },
      {
        field_name: 'root_cause',
        label: 'Root Cause',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 13,
        min_width: '20rem',
      },
      {
        field_name: 'tags',
        label: 'Tags',
        field_type: 'tags',
        data_type: 'array',
        show_in_table: true,
        show_in_form: true,
        display_order: 30,
        min_width: '14rem',
      },
    ],
  };

  // Upsert fields for each ticket type
  for (const [typeCode, fields] of Object.entries(fieldsByTicketType)) {
    const ticketTypeUuid = ticketTypeMap[typeCode];
    
    if (!ticketTypeUuid) {
      console.log(`  Skipping ${typeCode} - ticket type not found`);
      continue;
    }

    console.log(`  Creating/updating fields for ticket type: ${typeCode}`);

    for (const field of fields) {
      await prisma.ticket_type_fields.upsert({
        where: {
          ticket_type_uuid_field_name: {
            ticket_type_uuid: ticketTypeUuid,
            field_name: field.field_name,
          },
        },
        update: { ...field, ticket_type_uuid: ticketTypeUuid },
        create: { ...field, ticket_type_uuid: ticketTypeUuid },
      });
    }

    console.log(`    Created ${fields.length} fields`);
  }

  console.log('Ticket type fields seeding completed!');
}

module.exports = { seedTicketTypeFields };
