const { prisma } = require('../client');

/**
 * Seed ticket type fields - Extended fields definition for each ticket type
 * These fields define what attributes are stored in tickets.extended_core_fields
 */
async function seedTicketTypeFields() {
  console.log('Seeding ticket type fields...');

  // Get ticket types UUIDs
  const ticketTypes = await prisma.ticket_types.findMany({
    select: { uuid: true, code: true },
  });

  const ticketTypeMap = {};
  for (const tt of ticketTypes) {
    ticketTypeMap[tt.code] = tt.uuid;
  }

  // Define extended fields for each ticket type
  const fieldsByTicketType = {
    TASK: [
      {
        field_name: 'initial_target_date',
        label: 'Initial Target Date',
        description: 'Original target completion date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        is_required: false,
        is_readonly: false,
        min_width: '10rem',
        display_order: 1,
      },
      {
        field_name: 'revised_target_date',
        label: 'Revised Target Date',
        description: 'Updated target completion date after postponements',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        is_required: false,
        is_readonly: false,
        min_width: '10rem',
        display_order: 2,
      },
      {
        field_name: 'postponement_count',
        label: 'Postponement Count',
        description: 'Number of times the task has been postponed',
        field_type: 'number',
        data_type: 'number',
        show_in_table: true,
        show_in_form: true,
        is_required: false,
        is_readonly: true,
        min_width: '8rem',
        display_order: 3,
        default_value: '0',
      },
    ],
    INCIDENT: [
      {
        field_name: 'symptoms_uuid',
        label: 'Symptoms',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'symptoms',
        relation_display: 'label',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 1,
        min_width: '12rem',
      },
      {
        field_name: 'impact',
        label: 'Impact',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 2,
        min_width: '8rem',
        options_source: '/incident_setup?metadata=IMPACT',
      },
      {
        field_name: 'urgency',
        label: 'Urgency',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 3,
        min_width: '8rem',
        options_source: '/incident_setup?metadata=URGENCY',
      },
      {
        field_name: 'priority',
        label: 'Priority',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 4,
        min_width: '8rem',
      },
      {
        field_name: 'contact_type',
        label: 'Contact Type',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 5,
        min_width: '10rem',
        options_source: '/contact_types',
      },
      {
        field_name: 'rel_service',
        label: 'Service',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'services',
        relation_display: 'name',
        show_in_table: true,
        show_in_form: true,
        display_order: 6,
        min_width: '12rem',
      },
      {
        field_name: 'rel_service_offerings',
        label: 'Service Offerings',
        field_type: 'relation',
        data_type: 'array',
        relation_object: 'service_offerings',
        relation_display: 'name',
        show_in_table: false,
        show_in_form: true,
        display_order: 7,
        min_width: '14rem',
      },
      {
        field_name: 'resolution_notes',
        label: 'Resolution Notes',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 10,
        min_width: '20rem',
      },
      {
        field_name: 'resolution_code',
        label: 'Resolution Code',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 11,
        min_width: '10rem',
        options_source: '/incident_setup?metadata=RESOLUTION_CODE',
      },
      {
        field_name: 'cause_code',
        label: 'Cause Code',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 12,
        min_width: '10rem',
        options_source: '/incident_setup?metadata=CAUSE_CODE',
      },
      {
        field_name: 'rel_problem_id',
        label: 'Related Problem',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'tickets',
        relation_display: 'title',
        show_in_table: false,
        show_in_form: true,
        display_order: 13,
        min_width: '14rem',
      },
      {
        field_name: 'rel_change_request',
        label: 'Related Change Request',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'tickets',
        relation_display: 'title',
        show_in_table: false,
        show_in_form: true,
        display_order: 14,
        min_width: '14rem',
      },
      {
        field_name: 'sla_assignation_due_at',
        label: 'SLA Assignation Due',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        is_readonly: true,
        display_order: 20,
        min_width: '12rem',
      },
      {
        field_name: 'assigned_to_at',
        label: 'Assigned At',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: false,
        show_in_form: true,
        is_readonly: true,
        display_order: 21,
        min_width: '12rem',
      },
      {
        field_name: 'sla_resolution_due_at',
        label: 'SLA Resolution Due',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        is_readonly: true,
        display_order: 22,
        min_width: '12rem',
      },
      {
        field_name: 'resolved_at',
        label: 'Resolved At',
        field_type: 'datetime',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        is_readonly: true,
        display_order: 23,
        min_width: '12rem',
      },
      {
        field_name: 'reopen_count',
        label: 'Reopen Count',
        field_type: 'number',
        data_type: 'number',
        show_in_table: true,
        show_in_form: true,
        is_readonly: true,
        display_order: 30,
        min_width: '8rem',
        default_value: '0',
      },
      {
        field_name: 'assignment_count',
        label: 'Assignment Count',
        field_type: 'number',
        data_type: 'number',
        show_in_table: false,
        show_in_form: true,
        is_readonly: true,
        display_order: 31,
        min_width: '8rem',
        default_value: '0',
      },
      {
        field_name: 'assignment_to_count',
        label: 'Assignment To Count',
        field_type: 'number',
        data_type: 'number',
        show_in_table: false,
        show_in_form: true,
        is_readonly: true,
        display_order: 32,
        min_width: '8rem',
        default_value: '0',
      },
      {
        field_name: 'standby_count',
        label: 'Standby Count',
        field_type: 'number',
        data_type: 'number',
        show_in_table: false,
        show_in_form: true,
        is_readonly: true,
        display_order: 33,
        min_width: '8rem',
        default_value: '0',
      },
    ],
    PROBLEM: [
      {
        field_name: 'rel_problem_categories_code',
        label: 'Problem Category',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 1,
        min_width: '12rem',
        options_source: '/problem_categories',
      },
      {
        field_name: 'impact',
        label: 'Impact',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 2,
        min_width: '8rem',
        options_source: '/incident_setup?metadata=IMPACT',
      },
      {
        field_name: 'urgency',
        label: 'Urgency',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 3,
        min_width: '8rem',
        options_source: '/incident_setup?metadata=URGENCY',
      },
      {
        field_name: 'rel_service',
        label: 'Service',
        field_type: 'relation',
        data_type: 'string',
        relation_object: 'services',
        relation_display: 'name',
        show_in_table: true,
        show_in_form: true,
        display_order: 4,
        min_width: '12rem',
      },
      {
        field_name: 'rel_service_offerings',
        label: 'Service Offerings',
        field_type: 'relation',
        data_type: 'array',
        relation_object: 'service_offerings',
        relation_display: 'name',
        show_in_table: false,
        show_in_form: true,
        display_order: 5,
        min_width: '14rem',
      },
      {
        field_name: 'symptoms_description',
        label: 'Symptoms Description',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 10,
        min_width: '20rem',
      },
      {
        field_name: 'workaround',
        label: 'Workaround',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 11,
        min_width: '20rem',
      },
      {
        field_name: 'root_cause',
        label: 'Root Cause',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 12,
        min_width: '20rem',
      },
      {
        field_name: 'definitive_solution',
        label: 'Definitive Solution',
        field_type: 'textarea',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 13,
        min_width: '20rem',
      },
      {
        field_name: 'target_resolution_date',
        label: 'Target Resolution Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 20,
        min_width: '10rem',
      },
      {
        field_name: 'actual_resolution_date',
        label: 'Actual Resolution Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 21,
        min_width: '10rem',
      },
      {
        field_name: 'actual_resolution_workload',
        label: 'Actual Resolution Workload',
        field_type: 'number',
        data_type: 'number',
        show_in_table: true,
        show_in_form: true,
        display_order: 22,
        min_width: '8rem',
        unit: 'hours',
      },
      {
        field_name: 'closure_justification',
        label: 'Closure Justification',
        field_type: 'text',
        data_type: 'string',
        show_in_table: false,
        show_in_form: true,
        display_order: 30,
        min_width: '20rem',
      },
    ],
    PROJECT: [
      {
        field_name: 'key',
        label: 'Project Key',
        description: 'Unique project identifier code',
        field_type: 'text',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        is_required: true,
        display_order: 1,
        min_width: '8rem',
        max_length: 10,
      },
      {
        field_name: 'start_date',
        label: 'Start Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 2,
        min_width: '10rem',
      },
      {
        field_name: 'end_date',
        label: 'End Date',
        field_type: 'date',
        data_type: 'date',
        show_in_table: true,
        show_in_form: true,
        display_order: 3,
        min_width: '10rem',
      },
      {
        field_name: 'issue_type_id',
        label: 'Issue Types',
        field_type: 'relation',
        data_type: 'array',
        relation_object: 'symptoms',
        relation_display: 'label',
        show_in_table: false,
        show_in_form: true,
        display_order: 4,
        min_width: '14rem',
      },
      {
        field_name: 'visibility',
        label: 'Visibility',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 5,
        min_width: '10rem',
        options_source: JSON.stringify([
          { label: 'Public', value: 'PUBLIC' },
          { label: 'Private', value: 'PRIVATE' },
          { label: 'Restricted', value: 'RESTRICTED' },
        ]),
      },
      {
        field_name: 'project_type',
        label: 'Project Type',
        field_type: 'select',
        data_type: 'string',
        show_in_table: true,
        show_in_form: true,
        display_order: 6,
        min_width: '10rem',
        options_source: '/project_setup?metadata=category',
      },
      {
        field_name: 'access_to_groups',
        label: 'Access Groups',
        field_type: 'relation',
        data_type: 'array',
        relation_object: 'groups',
        relation_display: 'group_name',
        show_in_table: false,
        show_in_form: true,
        display_order: 10,
        min_width: '14rem',
      },
      {
        field_name: 'access_to_users',
        label: 'Access Users',
        field_type: 'relation',
        data_type: 'array',
        relation_object: 'persons',
        relation_display: 'last_name',
        show_in_table: false,
        show_in_form: true,
        display_order: 11,
        min_width: '14rem',
      },
    ],
  };

  // Upsert fields for each ticket type
  for (const [typeCode, fields] of Object.entries(fieldsByTicketType)) {
    const ticketTypeUuid = ticketTypeMap[typeCode];
    
    if (!ticketTypeUuid) {
      console.log(`  Skipping ${typeCode} - ticket type not found`);
      continue;
    }

    console.log(`  Creating/updating fields for ticket type: ${typeCode}`);

    for (const field of fields) {
      await prisma.ticket_type_fields.upsert({
        where: {
          ticket_type_uuid_field_name: {
            ticket_type_uuid: ticketTypeUuid,
            field_name: field.field_name,
          },
        },
        update: { ...field, ticket_type_uuid: ticketTypeUuid },
        create: { ...field, ticket_type_uuid: ticketTypeUuid },
      });
    }

    console.log(`    Created ${fields.length} fields`);
  }

  console.log('Ticket type fields seeding completed!');
}

module.exports = { seedTicketTypeFields };
